### PR TITLE
Update runtime-version to 45

### PR DESCRIPTION
**Pull request by NadjibC**

### CODE REVIEW

**Comment by NadjibC** [comment]
```
-- Checking for module 'webkit2gtk-5.0>=2.36.0'
--   Package 'webkit2gtk-5.0', required by 'virtual:world', not found
CMake Error at cmake/modules/PkgConfigEx.cmake:32 (message):
  Necessary libraries not found or not enough version.  If you want to
  disable WebKitGTK gtk4 for built-in OAuth2 authentications, please use
  -DENABLE_OAUTH2_WEBKITGTK4=OFF argument to cmake command.
Call Stack (most recent call first):
  CMakeLists.txt:426 (pkg_check_modules_for_option)
```

Dependency Issue has been caused by 'evolution-data-server', adding "-DENABLE_OAUTH2_WEBKITGTK4=OFF" to 'evolution-data-server' config-opts solves the problem by disabling WebKitGTK gtk4 for built-in OAuth2 authentications.

I don't know if Disabling WebKitGTK will break any functionality of the program. So it's better for me to stop at this point.

**Comment by NadjibC** [comment]
bot, rebuild

**Comment by NadjibC** [comment]
bot, build

**Comment by NadjibC** [comment]
Gnome Todo seems to be working Properly without "OATH2_WEBKITGTK"

**Comment by ItsJamie9494** [comment]
Thank you!

Yeah, it shouldn't need WebKit to my knowledge. If it does, then it's probably some super old, broken code anyways

**Pull request merged**
