### PR TITLE
Update runtime to 3.36 and dependencies

### LINKED ISSUE #5: Update runtime to v3.32

### PR DESCRIPTION
**Pull request by corecontingency**
Let's have a moment of silence for the other pull requests. They had so much to live for. :cry: :sob: 

Fixes #5, #4 and #8 .

### CODE REVIEW

**Comment by corecontingency** [comment]
Flatpak is compiling fine, but it looks like there are some problems with the upstream appdata.xml. Fun!

**Comment by corecontingency** [comment]
Seems to work fine. Ready to merge!

**Comment by corecontingency** [comment]
@TingPing When you have a chance, can you merge this PR? Currently, this flatpak is using the GNOME 3.30 runtime, which has been end-of-life for a long time.

**Comment by fixinggunsinair** [comment]
Is this package unmaintained?

**Comment by corecontingency** [comment]
> Is this package unmaintained?

Not sure, I just fixed it since I am using GNOME and would like to use this flatpak.

I'd be happy to take over as a maintainer though!

**Comment by corecontingency** [comment]
Rebased to update to version 3.36.2 of evolution-data-server.

Ready to merge.

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
