### PR TITLE
Update to runtime 40 along with dependencies

### LINKED ISSUE #10: GNOME 3.36 runtime is EOL as of Feb 13,2021.
https://www.reddit.com/r/openSUSE/comments/mf27xm/gnome_336_runtime_is_eol_as_of_feb_132021_when/

### PR DESCRIPTION
**Pull request by X-m7**
Fixes #10.

I had to disable Canberra support in evolution-data-server explicitly since it defaults to on, and I assume it wasn't used anyway seeing as Canberra wasn't in the manifest. There was also an update to intltool in shared-modules, so I updated it as well.

### CODE REVIEW

**Comment by X-m7** [comment]
bot, build

**Comment by X-m7** [comment]
Runs for me on Fedora Silverblue 34 beta with GNOME 40.0.

**Comment by nickavem** [comment]
> Build [43115 successful](https://flathub.org/builds/#/builders/32/builds/43115)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/41479/org.gnome.Todo.flatpakref
> ```

Works

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
